import random
RemainingLetters = [
    # Pulli (pure consonant, no vowel) versions
    [{"letter": "ங்", "correct": "ng"},
    {"letter": "ச்", "correct": "s/ch"},
    {"letter": "ஞ்", "correct": "ny"},
    {"letter": "ட்", "correct": "t"},
    {"letter": "ண்", "correct": "n"},
    {"letter": "த்", "correct": "th"},
    {"letter": "ந்", "correct": "n"},
    {"letter": "ப்", "correct": "p"},
    {"letter": "ம்", "correct": "m"},
    {"letter": "ய்", "correct": "y"},
    {"letter": "ர்", "correct": "r"},
    {"letter": "ல்", "correct": "l"},
    {"letter": "வ்", "correct": "v"},
    {"letter": "ழ்", "correct": "zh"},
    {"letter": "ள்", "correct": "l"},
    {"letter": "ற்", "correct": "r"},
    {"letter": "ன்", "correct": "n"}],

    # All other modified consonants
   [{"letter": "ஙா", "correct": "ngaa"},
    {"letter": "ஙி", "correct": "ngi"},
    {"letter": "ஙீ", "correct": "ngee"},
    {"letter": "ஙு", "correct": "ngu"},
    {"letter": "ஙூ", "correct": "nguu"},
    {"letter": "ஙெ", "correct": "ngae"},
    {"letter": "ஙே", "correct": "ngae"},
    {"letter": "ஙை", "correct": "ngai"},
    {"letter": "ஙொ", "correct": "ngoh"},
    {"letter": "ஙோ", "correct": "ngohh"},
    {"letter": "ஙௌ", "correct": "ngau"}],


    [{"letter": "ஞா", "correct": "nyaa"},
    {"letter": "ஞி", "correct": "nyi"},
    {"letter": "ஞீ", "correct": "nyee"},
    {"letter": "ஞு", "correct": "nyu"},
    {"letter": "ஞூ", "correct": "nyuu"},
    {"letter": "ஞெ", "correct": "nyae"},
    {"letter": "ஞே", "correct": "nyaee"},
    {"letter": "ஞை", "correct": "nyai"},
    {"letter": "ஞொ", "correct": "nyoh"},
    {"letter": "ஞோ", "correct": "nyohh"},
    {"letter": "ஞௌ", "correct": "nyau"}],

    [{"letter": "டா", "correct": "taa"},
    {"letter": "டி", "correct": "ti"},
    {"letter": "டீ", "correct": "tee"},
    {"letter": "டு", "correct": "tu"},
    {"letter": "டூ", "correct": "tuu"},
    {"letter": "டெ", "correct": "tae"},
    {"letter": "டே", "correct": "taee"},
    {"letter": "டை", "correct": "tai"},
    {"letter": "டொ", "correct": "toh"},
    {"letter": "டோ", "correct": "tohh"},
    {"letter": "டௌ", "correct": "tau"}],

    [{"letter": "ணா", "correct": "naa"},
    {"letter": "ணி", "correct": "ni"},
    {"letter": "ணீ", "correct": "nee"},
    {"letter": "ணு", "correct": "nu"},
    {"letter": "ணூ", "correct": "nuu"},
    {"letter": "ணெ", "correct": "nae"},
    {"letter": "ணே", "correct": "naee"},
    {"letter": "ணை", "correct": "nai"},
    {"letter": "ணொ", "correct": "noh"},
    {"letter": "ணோ", "correct": "nohh"},
    {"letter": "ணௌ", "correct": "nau"}],

    [{"letter": "தா", "correct": "thaa"},
    {"letter": "தி", "correct": "thi"},
    {"letter": "தீ", "correct": "thee"},
    {"letter": "து", "correct": "thu"},
    {"letter": "தூ", "correct": "thuu"},
    {"letter": "தெ", "correct": "thae"},
    {"letter": "தே", "correct": "thaee"},
    {"letter": "தை", "correct": "thai"},
    {"letter": "தொ", "correct": "thoh"},
    {"letter": "தோ", "correct": "thohh"},
    {"letter": "தௌ", "correct": "thau"}],

    [{"letter": "நா", "correct": "naa"},
    {"letter": "நி", "correct": "ni"},
    {"letter": "நீ", "correct": "nee"},
    {"letter": "நு", "correct": "nu"},
    {"letter": "நூ", "correct": "nuu"},
    {"letter": "நெ", "correct": "nae"},
    {"letter": "நே", "correct": "naee"},
    {"letter": "நை", "correct": "nai"},
    {"letter": "நொ", "correct": "noh"},
    {"letter": "நோ", "correct": "nohh"},
    {"letter": "நௌ", "correct": "nau"}],

    [{"letter": "பா", "correct": "paa"},
    {"letter": "பி", "correct": "pi"},
    {"letter": "பீ", "correct": "pee"},
    {"letter": "பு", "correct": "pu"},
    {"letter": "பூ", "correct": "puu"},
    {"letter": "பெ", "correct": "pae"},
    {"letter": "பே", "correct": "paee"},
    {"letter": "பை", "correct": "pai"},
    {"letter": "பொ", "correct": "poh"},
    {"letter": "போ", "correct": "pohh"},
    {"letter": "பௌ", "correct": "pau"}],

   [{"letter": "மா", "correct": "maa"},
    {"letter": "மி", "correct": "mi"},
    {"letter": "மீ", "correct": "mee"},
    {"letter": "மு", "correct": "mu"},
    {"letter": "மூ", "correct": "muu"},
    {"letter": "மெ", "correct": "mae"},
    {"letter": "மே", "correct": "maee"},
    {"letter": "மை", "correct": "mai"},
    {"letter": "மொ", "correct": "moh"},
    {"letter": "மோ", "correct": "mohh"},
    {"letter": "மௌ", "correct": "mau"}],

    [{"letter": "யா", "correct": "yaa"},
    {"letter": "யி", "correct": "yi"},
    {"letter": "யீ", "correct": "yee"},
    {"letter": "யு", "correct": "yu"},
    {"letter": "யூ", "correct": "yuu"},
    {"letter": "யெ", "correct": "yae"},
    {"letter": "யே", "correct": "yaee"},
    {"letter": "யை", "correct": "yai"},
    {"letter": "யொ", "correct": "yoh"},
    {"letter": "யோ", "correct": "yohh"},
    {"letter": "யௌ", "correct": "yau"}],

   [{"letter": "ரா", "correct": "raa"},
    {"letter": "ரி", "correct": "ri"},
    {"letter": "ரீ", "correct": "ree"},
    {"letter": "ரு", "correct": "ru"},
    {"letter": "ரூ", "correct": "ruu"},
    {"letter": "ரெ", "correct": "rae"},
    {"letter": "ரே", "correct": "raee"},
    {"letter": "ரை", "correct": "rai"},
    {"letter": "ரொ", "correct": "roh"},
    {"letter": "ரோ", "correct": "rohh"},
    {"letter": "ரௌ", "correct": "rau"}],

   [{"letter": "லா", "correct": "laa"},
    {"letter": "லி", "correct": "li"},
    {"letter": "லீ", "correct": "lee"},
    {"letter": "லு", "correct": "lu"},
    {"letter": "லூ", "correct": "luu"},
    {"letter": "லெ", "correct": "lae"},
    {"letter": "லே", "correct": "laee"},
    {"letter": "லை", "correct": "lai"},
    {"letter": "லொ", "correct": "loh"},
    {"letter": "லோ", "correct": "lohh"},
    {"letter": "லௌ", "correct": "lau"}],

   [{"letter": "வா", "correct": "vaa"},
    {"letter": "வி", "correct": "vi"},
    {"letter": "வீ", "correct": "vee"},
    {"letter": "வு", "correct": "vu"},
    {"letter": "வூ", "correct": "vuu"},
    {"letter": "வெ", "correct": "vae"},
    {"letter": "வே", "correct": "vaee"},
    {"letter": "வை", "correct": "vai"},
    {"letter": "வொ", "correct": "voh"},
    {"letter": "வோ", "correct": "vohh"},
    {"letter": "வௌ", "correct": "vau"}],

    [{"letter": "ழா", "correct": "zhaa"},
    {"letter": "ழி", "correct": "zhi"},
    {"letter": "ழீ", "correct": "zhee"},
    {"letter": "ழு", "correct": "zhu"},
    {"letter": "ழூ", "correct": "zhuu"},
    {"letter": "ழெ", "correct": "zhae"},
    {"letter": "ழே", "correct": "zhaee"},
    {"letter": "ழை", "correct": "zhai"},
    {"letter": "ழொ", "correct": "zhoh"},
    {"letter": "ழோ", "correct": "zhohh"},
    {"letter": "ழௌ", "correct": "zhau"}],

    [{"letter": "ளா", "correct": "laa"},
    {"letter": "ளி", "correct": "li"},
    {"letter": "ளீ", "correct": "lee"},
    {"letter": "ளு", "correct": "lu"},
    {"letter": "ளூ", "correct": "luu"},
    {"letter": "ளெ", "correct": "lae"},
    {"letter": "ளே", "correct": "laee"},
    {"letter": "ளை", "correct": "lai"},
    {"letter": "ளொ", "correct": "loh"},
    {"letter": "ளோ", "correct": "lohh"},
    {"letter": "ளௌ", "correct": "lau"}],

    [{"letter": "றா", "correct": "raa"},
    {"letter": "றி", "correct": "ri"},
    {"letter": "றீ", "correct": "ree"},
    {"letter": "று", "correct": "ru"},
    {"letter": "றூ", "correct": "ruu"},
    {"letter": "றெ", "correct": "rae"},
    {"letter": "றே", "correct": "raee"},
    {"letter": "றை", "correct": "rai"},
    {"letter": "றொ", "correct": "roh"},
    {"letter": "றோ", "correct": "rohh"},
    {"letter": "றௌ", "correct": "rau"}],

    [{"letter": "னா", "correct": "naa"},
    {"letter": "னி", "correct": "ni"},
    {"letter": "னீ", "correct": "nee"},
    {"letter": "னு", "correct": "nu"},
    {"letter": "னூ", "correct": "nuu"},
    {"letter": "னெ", "correct": "nae"},
    {"letter": "னே", "correct": "naee"},
    {"letter": "னை", "correct": "nai"}]
]

idx = 7
RemainingLessons = []
for i in range(len(RemainingLetters)):
    lesson = []
    lesson = random.sample(RemainingLetters[i], 3)
    for item in lesson:
        RemainingLetters[i].remove(item)
    for i in range(1,4):
        altLesson = random.randint(0, len(RemainingLessons))
        lesson.append(random.sample(RemainingLetters[altLesson], 1))
    pass
    idx+=1
    RemainingLessons.append({f'Lesson {idx} ', str(lesson)})
pass
print(RemainingLessons)